language: node_js
node_js:
  - 4
  - 6
  - 7
cache:
  directories:
  - node_modules
  - $HOME/.yarn-cache
before_install:
  - npm i -g yarn
install:
  - yarn --pure-lock
script:
  - yarn build
  - yarn test
